/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc.dao;

import java.util.Date;
import jdbc.dto.*;
import jdbc.exceptions.*;

public interface CampaignDao
{
	/** 
	 * Inserts a new row in the CAMPAIGN table.
	 */
	public CampaignPk insert(Campaign dto) throws CampaignDaoException;

	/** 
	 * Updates a single row in the CAMPAIGN table.
	 */
	public void update(CampaignPk pk, Campaign dto) throws CampaignDaoException;

	/** 
	 * Deletes a single row in the CAMPAIGN table.
	 */
	public void delete(CampaignPk pk) throws CampaignDaoException;

	/** 
	 * Returns the rows from the CAMPAIGN table that matches the specified primary-key value.
	 */
	public Campaign findByPrimaryKey(CampaignPk pk) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria 'ID = :id'.
	 */
	public Campaign findByPrimaryKey(int id) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria ''.
	 */
	public Campaign[] findAll() throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria 'ID = :id'.
	 */
	public Campaign[] findWhereIdEquals(int id) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria 'NAME = :name'.
	 */
	public Campaign[] findWhereNameEquals(String name) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria 'DESCRIPTION = :description'.
	 */
	public Campaign[] findWhereDescriptionEquals(String description) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria 'BEGIN = :begin'.
	 */
	public Campaign[] findWhereBeginEquals(Date begin) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the criteria 'END = :end'.
	 */
	public Campaign[] findWhereEndEquals(Date end) throws CampaignDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the CAMPAIGN table that match the specified arbitrary SQL statement
	 */
	public Campaign[] findByDynamicSelect(String sql, Object[] sqlParams) throws CampaignDaoException;

	/** 
	 * Returns all rows from the CAMPAIGN table that match the specified arbitrary SQL statement
	 */
	public Campaign[] findByDynamicWhere(String sql, Object[] sqlParams) throws CampaignDaoException;

}
