/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc.factory;

import java.sql.Connection;
import jdbc.dao.*;
import jdbc.jdbc.*;

public class CampaignDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return CampaignDao
	 */
	public static CampaignDao create()
	{
		return new CampaignDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return CampaignDao
	 */
	public static CampaignDao create(Connection conn)
	{
		return new CampaignDaoImpl( conn );
	}

}
