/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc.dto;

import jdbc.dao.*;
import jdbc.factory.*;
import jdbc.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CampaignUsers implements Serializable
{
	/** 
	 * This attribute maps to the column CAMPAIGN_ID in the CAMPAIGN_USERS table.
	 */
	protected int campaignId;

	/** 
	 * This attribute represents whether the primitive attribute campaignId is null.
	 */
	protected boolean campaignIdNull = true;

	/** 
	 * This attribute maps to the column USER_ID in the CAMPAIGN_USERS table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull = true;

	/**
	 * Method 'CampaignUsers'
	 * 
	 */
	public CampaignUsers()
	{
	}

	/**
	 * Method 'getCampaignId'
	 * 
	 * @return int
	 */
	public int getCampaignId()
	{
		return campaignId;
	}

	/**
	 * Method 'setCampaignId'
	 * 
	 * @param campaignId
	 */
	public void setCampaignId(int campaignId)
	{
		this.campaignId = campaignId;
		this.campaignIdNull = false;
	}

	/**
	 * Method 'setCampaignIdNull'
	 * 
	 * @param value
	 */
	public void setCampaignIdNull(boolean value)
	{
		this.campaignIdNull = value;
	}

	/**
	 * Method 'isCampaignIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isCampaignIdNull()
	{
		return campaignIdNull;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdNull = false;
	}

	/**
	 * Method 'setUserIdNull'
	 * 
	 * @param value
	 */
	public void setUserIdNull(boolean value)
	{
		this.userIdNull = value;
	}

	/**
	 * Method 'isUserIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CampaignUsers)) {
			return false;
		}
		
		final CampaignUsers _cast = (CampaignUsers) _other;
		if (campaignId != _cast.campaignId) {
			return false;
		}
		
		if (campaignIdNull != _cast.campaignIdNull) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + campaignId;
		_hashCode = 29 * _hashCode + (campaignIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "jdbc.dto.CampaignUsers: " );
		ret.append( "campaignId=" + campaignId );
		ret.append( ", userId=" + userId );
		return ret.toString();
	}

}
