/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc.dto;

import jdbc.dao.*;
import jdbc.factory.*;
import jdbc.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Campaign implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the CAMPAIGN table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column NAME in the CAMPAIGN table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column DESCRIPTION in the CAMPAIGN table.
	 */
	protected String description;

	/** 
	 * This attribute maps to the column BEGIN in the CAMPAIGN table.
	 */
	protected Date begin;

	/** 
	 * This attribute maps to the column END in the CAMPAIGN table.
	 */
	protected Date end;

	/**
	 * Method 'Campaign'
	 * 
	 */
	public Campaign()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'getBegin'
	 * 
	 * @return Date
	 */
	public Date getBegin()
	{
		return begin;
	}

	/**
	 * Method 'setBegin'
	 * 
	 * @param begin
	 */
	public void setBegin(Date begin)
	{
		this.begin = begin;
	}

	/**
	 * Method 'getEnd'
	 * 
	 * @return Date
	 */
	public Date getEnd()
	{
		return end;
	}

	/**
	 * Method 'setEnd'
	 * 
	 * @param end
	 */
	public void setEnd(Date end)
	{
		this.end = end;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Campaign)) {
			return false;
		}
		
		final Campaign _cast = (Campaign) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		if (begin == null ? _cast.begin != begin : !begin.equals( _cast.begin )) {
			return false;
		}
		
		if (end == null ? _cast.end != end : !end.equals( _cast.end )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		if (begin != null) {
			_hashCode = 29 * _hashCode + begin.hashCode();
		}
		
		if (end != null) {
			_hashCode = 29 * _hashCode + end.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CampaignPk
	 */
	public CampaignPk createPk()
	{
		return new CampaignPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "jdbc.dto.Campaign: " );
		ret.append( "id=" + id );
		ret.append( ", name=" + name );
		ret.append( ", description=" + description );
		ret.append( ", begin=" + begin );
		ret.append( ", end=" + end );
		return ret.toString();
	}

}
