/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc.dto;

import jdbc.dao.*;
import jdbc.factory.*;
import jdbc.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Message implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the MESSAGE table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column CAMPAIGN_ID in the MESSAGE table.
	 */
	protected int campaignId;

	/** 
	 * This attribute represents whether the primitive attribute campaignId is null.
	 */
	protected boolean campaignIdNull = true;

	/** 
	 * This attribute maps to the column USER_ID in the MESSAGE table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull = true;

	/** 
	 * This attribute maps to the column MESSAGE in the MESSAGE table.
	 */
	protected String message;

	/**
	 * Method 'Message'
	 * 
	 */
	public Message()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getCampaignId'
	 * 
	 * @return int
	 */
	public int getCampaignId()
	{
		return campaignId;
	}

	/**
	 * Method 'setCampaignId'
	 * 
	 * @param campaignId
	 */
	public void setCampaignId(int campaignId)
	{
		this.campaignId = campaignId;
		this.campaignIdNull = false;
	}

	/**
	 * Method 'setCampaignIdNull'
	 * 
	 * @param value
	 */
	public void setCampaignIdNull(boolean value)
	{
		this.campaignIdNull = value;
	}

	/**
	 * Method 'isCampaignIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isCampaignIdNull()
	{
		return campaignIdNull;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdNull = false;
	}

	/**
	 * Method 'setUserIdNull'
	 * 
	 * @param value
	 */
	public void setUserIdNull(boolean value)
	{
		this.userIdNull = value;
	}

	/**
	 * Method 'isUserIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/**
	 * Method 'getMessage'
	 * 
	 * @return String
	 */
	public String getMessage()
	{
		return message;
	}

	/**
	 * Method 'setMessage'
	 * 
	 * @param message
	 */
	public void setMessage(String message)
	{
		this.message = message;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Message)) {
			return false;
		}
		
		final Message _cast = (Message) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (campaignId != _cast.campaignId) {
			return false;
		}
		
		if (campaignIdNull != _cast.campaignIdNull) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		if (message == null ? _cast.message != message : !message.equals( _cast.message )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + campaignId;
		_hashCode = 29 * _hashCode + (campaignIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		if (message != null) {
			_hashCode = 29 * _hashCode + message.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MessagePk
	 */
	public MessagePk createPk()
	{
		return new MessagePk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "jdbc.dto.Message: " );
		ret.append( "id=" + id );
		ret.append( ", campaignId=" + campaignId );
		ret.append( ", userId=" + userId );
		ret.append( ", message=" + message );
		return ret.toString();
	}

}
