/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc.dto;

import jdbc.dao.*;
import jdbc.factory.*;
import jdbc.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class SentMessages implements Serializable
{
	/** 
	 * This attribute maps to the column USER_ID in the SENT_MESSAGES table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull = true;

	/** 
	 * This attribute maps to the column MESSAGE_ID in the SENT_MESSAGES table.
	 */
	protected int messageId;

	/** 
	 * This attribute represents whether the primitive attribute messageId is null.
	 */
	protected boolean messageIdNull = true;

	/** 
	 * This attribute maps to the column SEND_DATE in the SENT_MESSAGES table.
	 */
	protected Date sendDate;

	/**
	 * Method 'SentMessages'
	 * 
	 */
	public SentMessages()
	{
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdNull = false;
	}

	/**
	 * Method 'setUserIdNull'
	 * 
	 * @param value
	 */
	public void setUserIdNull(boolean value)
	{
		this.userIdNull = value;
	}

	/**
	 * Method 'isUserIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/**
	 * Method 'getMessageId'
	 * 
	 * @return int
	 */
	public int getMessageId()
	{
		return messageId;
	}

	/**
	 * Method 'setMessageId'
	 * 
	 * @param messageId
	 */
	public void setMessageId(int messageId)
	{
		this.messageId = messageId;
		this.messageIdNull = false;
	}

	/**
	 * Method 'setMessageIdNull'
	 * 
	 * @param value
	 */
	public void setMessageIdNull(boolean value)
	{
		this.messageIdNull = value;
	}

	/**
	 * Method 'isMessageIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isMessageIdNull()
	{
		return messageIdNull;
	}

	/**
	 * Method 'getSendDate'
	 * 
	 * @return Date
	 */
	public Date getSendDate()
	{
		return sendDate;
	}

	/**
	 * Method 'setSendDate'
	 * 
	 * @param sendDate
	 */
	public void setSendDate(Date sendDate)
	{
		this.sendDate = sendDate;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SentMessages)) {
			return false;
		}
		
		final SentMessages _cast = (SentMessages) _other;
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		if (messageId != _cast.messageId) {
			return false;
		}
		
		if (messageIdNull != _cast.messageIdNull) {
			return false;
		}
		
		if (sendDate == null ? _cast.sendDate != sendDate : !sendDate.equals( _cast.sendDate )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + messageId;
		_hashCode = 29 * _hashCode + (messageIdNull ? 1 : 0);
		if (sendDate != null) {
			_hashCode = 29 * _hashCode + sendDate.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "jdbc.dto.SentMessages: " );
		ret.append( "userId=" + userId );
		ret.append( ", messageId=" + messageId );
		ret.append( ", sendDate=" + sendDate );
		return ret.toString();
	}

}
